name: Update Changelog

on:
  pull_request:
    types:
      - open

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Changelog Script
        run: |
          python path/to/changelog_script.py ${{ github.event.pull_request.number }}